# Generated by Django 4.2 on 2023-04-16 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=127)),
                ('duration', models.CharField(max_length=10, null=True)),
                ('rating', models.CharField(choices=[('G', 'Rated G'), ('PG', 'Rated PG'), ('PG-13', 'Rated PG-13'), ('R', 'Rated R'), ('NC-17', 'Rated NC-17')], default='G', max_length=20)),
                ('synopse', models.TextField(null=True)),
            ],
        ),
    ]
