# Generated by Django 4.2 on 2023-04-16 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_alter_movie_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='duration',
            field=models.CharField(default=None, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='movie',
            name='synopse',
            field=models.TextField(default=None, null=True),
        ),
    ]
