# Generated by Django 4.2 on 2023-04-16 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_alter_movie_duration_alter_movie_synopse'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='synopse',
            new_name='synopsis',
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.CharField(choices=[('G', 'G'), ('PG', 'Pg'), ('PG-13', 'Pg13'), ('R', 'R'), ('NC-17', 'Nc17')], default='G', max_length=20),
        ),
    ]
