# Generated by Django 4.2 on 2023-04-17 00:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0004_rename_synopse_movie_synopsis_alter_movie_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='added_by',
            field=models.EmailField(default="eliasjp@gmail.com", max_length=254),
            preserve_default=False,
        ),
    ]
