# Generated by Django 4.2 on 2023-04-17 22:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0006_rename_added_by_movie_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='movie',
            old_name='user',
            new_name='added_by',
        ),
    ]
