# Generated by Django 4.2 on 2023-04-18 02:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('movies', '0007_rename_user_movie_added_by'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('buyed_at', models.DateField(auto_now_add=True)),
                ('buyed_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='buyer_email', to=settings.AUTH_USER_MODEL)),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='movie_title', to='movies.movie')),
            ],
        ),
    ]
