# Generated by Django 4.2 on 2023-04-18 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_remove_movie_added_by_movie_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieorder',
            name='buyed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
